### PR TITLE
* Dockerfile specific for RHEL

### PR DESCRIPTION
**Pull request by fatherlinux**
Scott M

### CODE REVIEW

**Comment by konstruktoid** [comment]
Long time no see @fatherlinux, can you resubmit this so it fits `docker-bench-security/distros`?

**Comment by fatherlinux** [comment]
I "believe" I have signed off correctly :-/ :-)

**Comment by fatherlinux** [comment]
Working on it now...

----- Original Message -----

**Comment by fatherlinux** [comment]
I think I finally fixed it?

**Comment by konstruktoid** [comment]
Yep, but why https://github.com/fatherlinux/docker-bench-security/commit/cf857e4388b9e180c67775fe8313724fc8fb422f?

And could you add the REPOSITORY and MAINTAINER instructions to the Dockerfiles as well, https://github.com/docker/docker-bench-security/blob/master/distros/README.md?

**Comment by fatherlinux** [comment]
That was a mistake, not sure how to undo it?
 I can add the maintainer stuff, no problem

**Comment by fatherlinux** [comment]
OK, I am literally terrible at going back and changing history :-(  I have NO IDEA how to fix that :-(

**Comment by konstruktoid** [comment]
No worries, it all can get pretty messy fast.

My recommendation is that you first get your master branch in sync with upstream, create a separate branch for the modifications, apply your changes and then submit a PR based on that new branch.

**Comment by fatherlinux** [comment]
Putting in a new pull request....

**Pull request closed without merging**
