### PR TITLE
Added -t target parameter and its description to README

### PR DESCRIPTION
**Pull request by halilkaya**
Updated -h output on README and added `-t TARGET` parameter to see by reading the README easily.

### CODE REVIEW

**Comment by konstruktoid** [comment]
I don't believe there is an `-t` option?
https://github.com/docker/docker-bench-security/blob/master/docker-bench-security.sh#L51-L57

**Comment by halilkaya** [comment]
Weird. Therefore, the current `docker/docker-bench-security:latest` image in the registry is different than the codebase. When I pull latest and run `-h`, the output is:

```sh
  usage: docker-bench-security.sh [options]

  -b           optional  Do not print colors
  -h           optional  Print this help message
  -l FILE      optional  Log output in FILE
  -c CHECK     optional  Comma delimited list of specific check(s)
  -e CHECK     optional  Comma delimited list of specific check(s) to exclude
  -i INCLUDE   optional  Comma delimited list of patterns within a container name to check
  -x EXCLUDE   optional  Comma delimited list of patterns within a container name to exclude from check
  -t TARGET    optional  Comma delimited list of images name to check
```

**Comment by konstruktoid** [comment]
You're correct @halilkaya the Docker image is out-of-date, please have a look at https://github.com/docker/docker-bench-security/issues/405

**Comment by halilkaya** [comment]
Oh, sorry. This parameter is removed 11 months ago.

https://github.com/docker/docker-bench-security/commit/ef206be6e0ed0a62fa2b17727472fc0c8bcd1a6e

OK, then. I'm closing the PR and waiting for the new release. :)

Thanks, @konstruktoid

**Pull request closed without merging**
