### PR TITLE
Created customized Dockerfiles for RHEL and CentOS

### PR DESCRIPTION
**Pull request by fatherlinux**
Signed-off-by: Scott McCarty <smccarty@redhat.com>

### CODE REVIEW

**Comment by fatherlinux** [comment]
OK, @konstruktoid, I think I figured out how to get a clean commit :-)

**Comment by konstruktoid** [comment]
Awesome! :+1:

Could you just change the REPOSITORY instruction to `# REPOSITORY https://github.com/fatherlinux/docker-bench-security` so the url points to your repository?

**Comment by fatherlinux** [comment]
Boom, done. Looks good :-)

**Comment by konstruktoid** [comment]
Thanks!

**Pull request merged**
