### PR TITLE
Created a much more sophisticated check for whether storage has really been moved off the root volume

### PR DESCRIPTION
**Pull request by fatherlinux**
been moved off the root volume

Signed-off-by: Scott McCarty smccarty@redhat.com

### CODE REVIEW

**Comment by fatherlinux** [comment]
Fixes issue #20

**Comment by konstruktoid** [comment]
Thanks for the PR but there is some issues with it.

Running on Ubuntu:
`stat: cannot stat ‘/etc/sysconfig/docker-storage’: No such file or directory
./docker-bench-security.sh: 297: [: Illegal number:`

Also please run `shellcheck tests/1_1_check.sh` or similar testing tools.
Last but not least, I think `THINPOOLDEV=`ps -ef | grep docker |` could be replaced by `get_command_line_args()`.

**Comment by fatherlinux** [comment]
@konstruktoid, that first error isn't from my code. I grepped the directory and  it looks like it is coming from section 1.17 of 1_host_configuration.sh

Also, I have never seen a way to get command line args from an already running process? I googled a little and found this which is similarly as nasty as my solution:

/bin/cat /proc/$PRID/cmdline | /bin/gawk -F[[:cntrl:]] '{ for ( i = 1; i < 
NF+1; i++ ) printf( "%s ", $i ) } { print "n" }'

I ran through ShellCheck and made some minor changes, tested with bash -x on RHEL6/RHEL7/RHEL7 Atomic....

**Comment by konstruktoid** [comment]
Yeah, it seems I have to go through the permission stuff again...

Anyway, I started to think that the partition checks in general seems a bit too complicated, so I went back to the books.
CIS: `1.1 Create a separate partition for containers (Scored)` says that the only audit that's required is `grep /var/lib/docker /etc/fstab`. This is an easy one to check.
But wouldn't it also be easier to check when `Storage Driver: devicemapper` the Data and Metadata files are stored on a non-/ partition and when `Storage Driver: aufs` the Root Dir is located on a separate partition. 

Another issue is that on Fedora 22 the `ps` returns `/usr/bin/docker -d --selinux-enabled --icc=false` even if Docker uses the devicemapper.

Compare
```sh
[tsj@fed ~]$ sudo docker info
Containers: 9
Images: 17
Storage Driver: devicemapper
 Pool Name: docker-253:1-100663443-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 427.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 16.89 GB
 Metadata Space Used: 1.585 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 4.0.6-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 1
Total Memory: 1.955 GiB
Name: fed
ID: IZOV:2OUN:4WTY:IDCS:E36L:DD6C:N35F:RFAQ:YD6G:PQ4T:ZUKN:PBJC
[tsj@fed ~]$
```
with
```sh
tsj@lab01:~$ sudo docker info
Containers: 2
Images: 30
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-20-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 1.954 GiB
Name: lab01
ID: 6AEH:63II:LVVM:TZPI:LSSA:U5LL:U27O:XJ22:TBY6:6BKS:MTEX:PVEG
WARNING: No swap limit support
Experimental: true
tsj@lab01:~$
```

Thoughts?

**Comment by fatherlinux** [comment]
So, ACTUALLY, I agree. I was half way through doing it the HARD way, and I checked the spec and thought to myself, I think we can do it with the other fields you mentioned. They are empty on RHEL and RHEL atomic, but as long as they are not equal to: ROOTVOLUME=$(df -P | grep " \/$" | awk '{print $1}') I think we are good...

I will poke with it...

**Comment by konstruktoid** [comment]
Thanks!

**Comment by konstruktoid** [comment]
Closing due to inactivity.

**Pull request closed without merging**
