### PR TITLE
Fix check conditions

### PR DESCRIPTION
**Pull request by zawazawa0316**
Signed-off-by: zawazawa0316 <37421794+zawazawa0316@users.noreply.github.com>

### CODE REVIEW

**Comment by konstruktoid** [comment]
Thanks for this PR as well, just some very minor nitpicking.

**Comment by zawazawa0316** [comment]
This is a sequel of https://github.com/docker/docker-bench-security/pull/418 .
Difference is only  5.31.

**Comment by konstruktoid** [comment]
Yeah, I know, but there's an extra space at ` if ` on line 230.

**Comment by zawazawa0316** [comment]
Thank you,Thank you, I fixed.

**Comment by konstruktoid** [comment]
Thanks!

**Pull request merged**
