### PR TITLE
Use compose to improve readability

### PR DESCRIPTION
**Pull request by lusitania**
IMO Docker Compose is a great tool to improve readability of Docker invocations. Here's the equivalent ``docker-compose.yml`` for the start-up config given in the README.md.

### CODE REVIEW

**Comment by diogomonica** [comment]
@lusitania great idea. Unfortunately, it doesn't seem to be working for me:

```
➜  docker-bench-security git:(have-compose) docker-compose --version
docker-compose version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
➜  docker-bench-security git:(have-compose) docker-compose up       
Invalid service name "docker_bench_security" - only [a-zA-Z0-9] are allowed
```

**Comment by lusitania** [comment]
@diogomonica I'll look into it. My case requires a separate build step (I had to force an update, see the current PR) which is why I'm a little surprised.

```
# docker-compose --version
docker-compose version: 1.4.1
```

**Comment by konstruktoid** [comment]
Nice idea @lusitania but there's some issues with the `path`:
```sh
$ docker-compose run --rm docker-bench-security
Unsupported config option for docker-bench-security service: 'path'
$ docker-compose --version
docker-compose version: 1.4.1
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   f018c04
 Built:        Mon Sep 21 17:54:52 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   f018c04
 Built:        Mon Sep 21 17:54:52 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
$ docker-compose up  docker-bench-security
Unsupported config option for docker-bench-security service: 'path'
$
```

**Comment by lusitania** [comment]
I found the error: Somewhere between testing and writing comments I must have mixed up the words. The config option for the build path is ``build``, not path. I'm changing it right away (and test again).

**Comment by lusitania** [comment]
Okay, changed, tested, committed, tested:
```sh
$ sudo docker images |grep ^docker-bench|wc -l
0

$ sudo docker-compose run --rm docker-bench-security

# ------------------------------------------------------------------------------
# Docker Bench for Security v1.0.0
#
# Docker, Inc. (c) 2015
#
# Checks for dozens of common best-practices around deploying Docker containers in production.
# Inspired by the CIS Docker 1.6 Benchmark:
# https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf
# ------------------------------------------------------------------------------

Initializing Sun Oct  4 12:19:45 CEST 2015


[INFO] 1 - Host Configuration
[WARN] 1.1  - Create a separate partition for containers
...
```

For completeness:
```sh
$ sudo docker-compose version
docker-compose version: 1.4.2
docker-py version: 1.3.1
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014

$ sudo docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by diogomonica** [comment]
@lusitania it now works for me, but it isn't excluding the docker-bench container itself:

```
docker-bench-security_1 | [PASS] 5.8  - Do not map privileged ports within containers
docker-bench-security_1 | [WARN] 5.10 - Do not use host network mode on container
docker-bench-security_1 | [WARN]      * Container running with networking mode 'host': dockerbenchsecurity_docker-bench-security_1
docker-bench-security_1 | [WARN] 5.11 - Limit memory usage for container
docker-bench-security_1 | [WARN]      * Container running without memory restrictions: dockerbenchsecurity_docker-bench-security_1
docker-bench-security_1 | [WARN] 5.12 - Set container CPU priority appropriately
docker-bench-security_1 | [WARN]      * Container running without CPU restrictions: dockerbenchsecurity_docker-bench-security_1
docker-bench-security_1 | [WARN] 5.13 - Mount container's root filesystem as read only
docker-bench-security_1 | [WARN]      * Container running with root FS mounted R/W: dockerbenchsecurity_docker-bench-security_1
docker-bench-security_1 | [PASS] 5.14 - Bind incoming container traffic to a specific host interface
docker-bench-security_1 | [PASS] 5.15 - Do not set the 'on-failure' container restart policy to always
docker-bench-security_1 | [WARN] 5.16 - Do not share the host's process namespace
docker-bench-security_1 | [WARN]      * Host PID namespace being shared with: dockerbenchsecurity_docker-bench-security_1
docker-bench-security_1 | [PASS] 5.17 - Do not share the host's IPC namespace
docker-bench-security_1 | [PASS] 5.18 - Do not directly expose host devices to containers
docker-bench-security_1 | [INFO] 5.19 - Override default ulimit at runtime only if needed
docker-bench-security_1 | [INFO]      * Container no default ulimit override: dockerbenchsecurity_docker-bench-security_1
```

**Comment by lusitania** [comment]
@diogomonica My change merely wraps the invocation documented in [README.md](/docker/docker-bench-security/blob/master/README.md). I haven't touched any tests.

**Comment by diogomonica** [comment]
@lusitania agreed, but unfortunately docker-bench uses a label ` --label docker_bench_security` to exclude itself from being tested, so I think we need to add an entry of `docker_bench_security` under `labels` on the docker-compose.yml file for this to still work.

See Labels here: https://github.com/docker/compose/blob/master/docs/yml.md

**Comment by lusitania** [comment]
Amended and forced a push.

I assumed the dashed label was required to start the service up properly. I was wrong, changed dashes to underscores.

**Comment by diogomonica** [comment]
Works great. Thank you for you contribution.

**Pull request merged**
